services:
  # ===================================
  # Sadece API Servisi (Free Tier Dostu)
  # ===================================
  - type: web
    name: poi-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: MONGODB_URI
        sync: false
      - key: SPRING_DATA_REDIS_HOST
        sync: false
      - key: SPRING_DATA_REDIS_PASSWORD
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: API_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      # Grafana Cloud Değişkenleri
      - key: GRAFANA_OTLP_ENDPOINT
        sync: false
      - key: GRAFANA_API_TOKEN_BASE64
        sync: false